### ISSUE TITLE
Visibility issue

### ISSUE THREAD

**Issue by grahamewebb-da** [digital-asset/ex-structured-products#11]
Issuer can now see Intermediary vs. Client trade due to the new divulgence properties with DAML.

**Steps**

1. Create Issuer vs. Intermediary trade proposal
2. Intermediary accepts trade proposal
3. Intermediary creates Intermediary vs. Client trade proposal
4. Client accepts trade proposal
5. Login as Issuer and Issuer can view the Intermediary vs. Client trade when this is not expected behaviour.

**Comment by gaborh-da** [comment]
You do not see the Intermediary vs. Client but the proposal. I think this is the "expected DAML behaviour" e.g. you see stuff resulted from exercising a choice on your contract (in this case you as the Issuer see TradeProposal resulted from exercising choice `ProposeTradeToClient` by Intermediary on your Trade contract).

**Comment by demian-da** [comment]
Hi All, I created a template `IntermediaryTradingRole` where issuer is just an observer. I moved `ProposeTradeToClient` into this template. In the MarketSetup scenario intermediary alone creates this role using its `IntermediaryRole`. (Uniqueness is enforced using intermediary as the tempalte key.)
